services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - my_pgdata:/var/lib/postgresql/data

  db-test:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres_test
    ports:
      - ${DB_TEST_PORT}:5432
    volumes:
      - my_pgdata_test:/var/lib/postgresql/data

volumes:
  my_pgdata:
    name: my_pgdata
    external: true
  my_pgdata_test:
